# Generated by Django 4.0.4 on 2022-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='is_user',
            field=models.BooleanField(null=True),
        ),
    ]
